site_name: Web App Tutorial
site_url: https://fkariminejadasl.github.io/web-app-tutorial/
nav:
  - Github from Markdown: github_md.md
  - Simple App: simple_app.md
  - Tools: tools.md
  - Tutorial:
      - Iframe: tutorial/iframe.md
theme:
  name: material #readthedocs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js